
# SEO settings
title: "Digging for "
title2: "Ideas" # default: ""
description: "..."
keywords: "linux, iot, artik"
url: http://webispy.github.io/ # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics:
repo: http://github.com/webispy
disqus_shortname: "webispy"
twitter_username: "webispy"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Inho Oh"
  job      : "Software Engineer"
  bio      : "."
  thumb    : /images/author.jpg
  email    : webispy@gmail.com
  url      : http://webispy.github.io
  github   : http://github.com/webispy
  linkedin : http://linkedin.com/in/webispy

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@webispy"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
